exports.TagData = [
    "Pencil Sketch",
    "Realistic Pencil Art",
    "Charcoal Drawing",
    "Portrait Drawing",
    "Illustration",
    "Line Art",
    "Black and White Art",
    "Surreal Pencil Art",
    "Abstract Pencil Drawing",
    "Doodle Art",
    "Digital Art",
    "Digital Painting",
    "Vector Art",
    "Digital Illustration",
    "Concept Art",
    "Anime and Manga Art",
    "Pixel Art",
    "Digital Portraits",
    "Fantasy Art",
    "Sci-Fi Art",
    "Abstract Digital Art",
    "Handmade Crafts",
    "DIY Crafts",
    "Paper Craft",
    "Origami",
    "Fabric Art",
    "Pottery",
    "Metal Craft",
    "Beadwork",
    "Recycled Art",
    "Mixed Media Art",
    "Collage Art",
    "Glass Art",
    "Sculpture",
    "Calligraphy",
    "Printmaking",
    "Mosaic Art",
    "3D Art",
    "Realism",
    "Abstract",
    "Impressionism",
    "Expressionism",
    "Cubism",
    "Modern Art",
    "Traditional Art",
    "Contemporary Art",
    "Nature Art",
    "Wildlife Art",
    "Portrait Art",
    "Landscape Art",
    "Mythology Art",
    "Acrylic Painting",
    "Oil Painting",
    "Watercolor Painting",
    "Ink Art",
    "Pastel Art",
    "Colored Pencil Art",
    "Digital Collage",
    "Mixed Media Collage",
    "Woodworking",
    "Wood Carving",
    "Leathercraft",
    "Candle Making",
    "Home Decor Crafts",
    "Polymer Clay Crafts",
    "Basket Weaving",
    "Knitting",
    "Crocheting",
    "Realistic Oil Portraits",
    "Traditional Illustration",
    "Still Life Painting",
    "Encaustic Art",
    "Traditional Printmaking",
    "Woodcut Prints",
    "Etching Art",
    "Marble Sculpting",
    "Stone Carving",
    "Clay Sculpture",
    "Traditional Portrait Drawing",
    "Figure Drawing",
    "Realism in Art",
    "Hyperrealism",
    "Impressionist Painting",
    "Abstract Expressionism",
    "Symbolist Art",
    "Surrealist Art",
    "Miniature Painting",
    "Creative drawing",
    "Innovative Drawing"
  ];
  